### PR TITLE
Added switches for Hot water generator

### PR DESCRIPTION
**Pull request by nao-pon**
@scottyphillips Thank you for developing a great component!

I have added some switches for Rinnai water heaters. I look forward to working with you.

### CODE REVIEW

**Comment by scottyphillips** [comment]
Wow that’s exciting new component! Let me digest the PR and I’ll approve it sometime this week. Perhaps later on you could also help me with a translation of the readme doco into 日本語? 😃

**Comment by scottyphillips** [comment]
Hey what’s binaly? Is that a typo for binary?

**Comment by nao-pon** [comment]
@scottyphillips Yes, it's typo. I fixed it and some changes are comitted.

And, of course, I will cooperate in translating the document into Japanese.

**Comment by scottyphillips** [comment]
Can we try to use an asyncio.sleep() rather then time.sleep()? Time.sleep is pretty brutal to the rest of Home assistant.

**Comment by nao-pon** [comment]
Yes, I used asyncio.sleep instead of time.sleep and checked the operation.

**Comment by nao-pon** [comment]
@scottyphillips I have more thoughts.
The Rinnai water heater parameter has a timer time, which can be set.
The timer time is related to the timer switch and I'm considering adding a service to the code of the switch entity.
Is it okay to think in this direction?

**Comment by scottyphillips** [comment]
Yes, but as long as you make it specific to your Hot water generator EOJCC and EOJGC. 
What I would do is register a service under this line in switch.py:
```
if entity['instance']['eojgc'] == 2 and entity['instance']['eojcc'] == 114:  # Hot water generator
# register your device specific service here eg async_set_hot_water_timer() 
```
The other thing I would like revised is your proposed switch schema in const.py and how it relates to the creation of sensors. 
At the moment I don't see that it is necessary to have both a sensor and a switch to represent the same EPC code. I would like to see some logic where sensors are not created if the EPC in question is designated as a switch entity. 

I would also like to see the switch codes be more generic so it can be use for other entities and more closely align with the sensor schema. In fact I have a great idea - combine the two together. 

So rather then 

```
HOTWATER_SWITCH_CODES = {
    0x80: {
        CONF_ICON: "mdi:power-settings",
        CONF_SERVICE_DATA: SWITCH_POWER
    },
    0x90: {
        CONF_ICON: "mdi:timer",
        CONF_SERVICE_DATA: SWITCH_BINARY,
        CONF_ENSURE_ON: 0x80
    },
    0xE3: {
        CONF_ICON: "mdi:bathtub-outline",
        CONF_SERVICE_DATA: SWITCH_BINARY,
        CONF_ENSURE_ON: 0x80
    },
    0xE4: {
        CONF_ICON: "mdi:heat-wave",
        CONF_SERVICE_DATA: SWITCH_BINARY,
        CONF_ENSURE_ON: 0x80
    }
}
```

make it look like this:

```
ENL_OP_CODES = { # change ENL_SENSOR_OP_CODES 
    0x00: {
        0x11: {
            0xE0: {     # existing sensor 
                CONF_ICON: "mdi:thermometer",
                CONF_TYPE: DEVICE_CLASS_TEMPERATURE,
                CONF_STATE_CLASS: STATE_CLASS_MEASUREMENT
            },
        }
    },
   0x01: { 
      0x114: {
          0x80: {     # switch
              CONF_ICON: "mdi:power-settings",
              CONF_SERVICE_DATA: SWITCH_POWER
              TYPE_SWITCH: True
          },
          0x90: {
              CONF_ICON: "mdi:timer",
              CONF_SERVICE_DATA: SWITCH_BINARY,
              CONF_ENSURE_ON: 0x80
              TYPE_SWITCH: True
          },
          0xE3: {
              CONF_ICON: "mdi:bathtub-outline",
              CONF_SERVICE_DATA: SWITCH_BINARY,
              CONF_ENSURE_ON: 0x80
              TYPE_SWITCH: True
          },
          0xE4: {
              CONF_ICON: "mdi:heat-wave",
              CONF_SERVICE_DATA: SWITCH_BINARY,
              CONF_ENSURE_ON: 0x80
              TYPE_SWITCH: True
          }
      }
}
```
For example line 57 of sensor.py:
```
        else:  # For all other devices, sensors will be configured but customise if applicable.
            for op_code in list(entity['echonetlite']._update_flags_full_list):
                if eojgc in ENL_OP_CODES.keys():
                    if eojcc in ENL_OP_CODES[eojgc].keys():
                        if op_code in ENL_OP_CODES[eojgc][eojcc].keys():
                            if TYPE_SWITCH in ENL_OP_CODES[eojgc][eojcc][op_code].keys():
                                 continue # dont configure as sensor, it will be configured as switch instead. 
                            entities.append(
                                EchonetSensor(
                                    entity['echonetlite'],
                                    op_code,
                                    ENL_SENSOR_OP_CODES[eojgc][eojcc][op_code],
                                    config.title
                                )
                            )
                            continue
                entities.append(
                    EchonetSensor(entity['echonetlite'], op_code, ENL_SENSOR_OP_CODES['default'], config.title)
                )
```

and then in your switch.py:
```
async def async_setup_entry(hass, config, async_add_entities, discovery_info=None):
    entities = []
    for entity in hass.data[DOMAIN][config.entry_id]:
            for op_code in list(entity['echonetlite']._update_flags_full_list):
                if eojgc in ENL_OP_CODES.keys():
                    if eojcc in ENL_OP_CODES[eojgc].keys():
                        if op_code in ENL_OP_CODES[eojgc][eojcc].keys():
                            if TYPE_SWITCH in ENL_OP_CODES[eojgc][eojcc][op_code].keys():
                                entities.append(
                                    EchonetSwitch(
                                       hass,
                                       entity['echonetlite'],
                                       config,
                                       op_code,
                                       ENL_OP_CODES[eojgc][eojcc][op_code],
                                       config.title
                                    )
                                )
    async_add_entities(entities, True)
```

Hopefully this all makes sense, I want to see the switch entity be as generic as possible so other devices can use it with a minimum of rework.

**Comment by scottyphillips** [comment]
This is just a bit of a rough outline:

```
async def async_setup_entry(hass, config, async_add_entities, discovery_info=None):
    entities = []
    for entity in hass.data[DOMAIN][config.entry_id]:
            # configure class specific service calls here
            if entity['instance']['eojgc'] == 2 and entity['instance']['eojcc'] == 114:  # Hot water generator
                  # register your device specific service here eg async_set_hot_water_timer() 

            # configure switch entities by looking up ENL_OP_CODE dict
            for op_code in list(entity['echonetlite']._update_flags_full_list):
                if eojgc in ENL_OP_CODES.keys():
                    if eojcc in ENL_OP_CODES[eojgc].keys():
                        if op_code in ENL_OP_CODES[eojgc][eojcc].keys():
                            if TYPE_SWITCH in ENL_OP_CODES[eojgc][eojcc][op_code].keys():
                                entities.append(
                                    EchonetSwitch(
                                       hass,
                                       entity['echonetlite'],
                                       config,
                                       op_code,
                                       ENL_OP_CODES[eojgc][eojcc][op_code],
                                       config.title
                                    )
                                )
    async_add_entities(entities, True)
```

**Comment by nao-pon** [comment]
@scottyphillips Yes, I think it's a reasonable implementation for sure. 👍 

I modify the code that way and commit again. 😄

**Comment by nao-pon** [comment]
@scottyphillips I'm stumbling on setting time with the service. For example, what should I do if I write "10:00" (hh: mm) to 0x91?

**Comment by scottyphillips** [comment]
Probably best to create a setHotWaterTimer() method in pychonet as part of the HotWaterHeater class and then car it directly in the service. So a bit of work to do there.

**Comment by nao-pon** [comment]
OK, Switch and sensor integrated, simplified and committed.

For services, I think it makes sense to handle them in a sensor entity. About that, HomeAssistan's processing is roughly done, but I would like to wait for your advice and make another PR.

**Comment by scottyphillips** [comment]
Looks good. Let’s manage the service creation under a separate body of work. I’ll approve the PR shortly once I test on my own system.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by scottyphillips** [comment]
Thanks for your contribution by the way! It's amazing how many people are using this for so many different devices now! Well beyond my own modest need!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nao-pon** [comment]
I publicized #78 with the addition of service functionality. You can choose either one and merge. If you choose #77, I will recreate #78.

Thanks! 😄

**Comment by nao-pon** [comment]
@scottyphillips Thank you for marge #78. 👍

**Pull request closed without merging**
