### PR TITLE
Electric blinds & covers

### PR DESCRIPTION
**Pull request by xen2**
Add support for blind and covers.
I will test it over next few days to make sure it doesn't degrade over time.

One issue I noticed is, if I issue a tilt command while blind is moving up/down, it will go back all the way up.
I assume this is probably a problem only with my specific blind system, so I was hesitating to make a workaround (i.e. wait until blind not moving before issuing tilt command).

Note: I had to filter `select` with `NON_SETUP_SINGLE_ENYITY` so that it doesn't appear anymore in the list (so far, only `sensor` were filtered). Maybe we want to generalize `NON_SETUP_SINGLE_ENYITY` to any other entity types as well?

### CODE REVIEW

**Comment by nao-pon** [comment]
It's true that select entities are no longer needed, but I think it's a good idea to disable them by default to ensure backwards compatibility.

This is possible by setting `CONF_DISABLED_DEFAULT: True`. It is disabled on new setups and has no impact on previously setup environments. Old users can be disabled at their own will.

```python
0xE0: {
    CONF_ICON: "mdi:boom-gate-up-outline",
    CONF_ICONS: {
        OPEN: "mdi:boom-gate-up-outline",
        CLOSE: "mdi:boom-gate-outline",
        STOP: "mdi:boom-gate-up-outline",
    },
    CONF_DISABLED_DEFAULT: True,
}
```

**Comment by xen2** [comment]
> It's true that select entities are no longer needed, but I think it's a good idea to disable them by default to ensure backwards compatibility.
> 
> This is possible by setting `CONF_DISABLED_DEFAULT: True`. It is disabled on new setups and has no impact on previously setup environments. Old users can be disabled at their own will.
> 
> ```python
> 0xE0: {
>     CONF_ICON: "mdi:boom-gate-up-outline",
>     CONF_ICONS: {
>         OPEN: "mdi:boom-gate-up-outline",
>         CLOSE: "mdi:boom-gate-outline",
>         STOP: "mdi:boom-gate-up-outline",
>     },
>     CONF_DISABLED_DEFAULT: True,
> }
> ```

Thanks for the hint. It's perfect for this situation, I will do this change!

**Comment by xen2** [comment]
After using it for a few days, it seems to work well enough!

**Comment by xen2** [comment]
FYI I didn't do the `CONF_DISABLED_DEFAULT` fix yet.

**Comment by nao-pon** [comment]
Yes, I'm currently doing maintenance on the cover entity.

**Comment by nao-pon** [comment]
@xen2 I maintained the Cover entity and applied it to my edge version. I don't have the actual machine so I can't verify it, so could you help me verify it?

edge version: https://github.com/nao-pon/echonetlite_homeassistant

If you add the above URL as a HACS custom repository, you will be able to install it with HACS.

**Comment by nao-pon** [comment]
@xen2 #177 was merged to master. Please try and verify of master version.

**Pull request merged**
